<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Report - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #4e73df;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #2e59d9;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }
        th {
            background-color: #4e73df;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .config-item {
            display: block;
            margin: 2px 0;
            font-size: 11px;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 11px;
            color: #666;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Product Inventory Report</h1>
        <p>Generated on: {{ now()->format('M d, Y h:i A') }}</p>
    </div>

    <div class="summary">
        <strong>Report Summary:</strong>
        Total Products: {{ $inventories->count() }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Brand</th>
                <th>Category</th>
                <th>IMEI</th>
                <th>Configuration</th>
                <th>Price (Tk)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($inventories as $inventory)
                @php
                    $attributes = json_decode($inventory->attribute_combination, true) ?? [];
                @endphp
                <tr>
                    <td>{{ $inventory->product->name ?? 'N/A' }}</td>
                    <td>{{ $inventory->product->brand->name ?? 'N/A' }}</td>
                    <td>{{ $inventory->product->category->name ?? 'N/A' }}</td>
                    <td>{{ $inventory->imei }}</td>
                    <td>
                        @foreach($attributes as $key => $value)
                            @php
                                $filter = App\Models\Filter::find($key);
                                $optionValue = App\Models\FilterOption::find($value);
                            @endphp

                            @if($filter && $optionValue)
                                <span class="config-item">
                                    <strong>{{ $filter->name }}:</strong> {{ $optionValue->value }}
                                </span>
                            @endif
                        @endforeach
                    </td>
                    <td style="text-align: right;">{{ number_format($inventory->selling_price, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No products found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by {{ auth()->user()->name ?? 'System' }}</p>
        {{-- <p>Page {{ $pdf->getPage() }} of {{ $pdf->getPageCount() }}</p> --}}
    </div>
</body>
</html>
