<!DOCTYPE html>
<html>
<head>
    <title>Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .title {
            font-size: 18px;
            font-weight: bold;
        }
        .date {
            font-size: 12px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
         td {
            font-size: 11px; /* Smaller font size for table cells */
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #666;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Sales Report</div>
        <div class="date">Generated on: {{ now()->format('M d, Y h:i A') }}</div>
    </div>

    @if(request()->start_date || request()->end_date || request()->customer_id)
    <div class="filters">
        <strong>Filters Applied:</strong><br>
        @if(request()->start_date)
        - Start Date: {{ request()->start_date }}<br>
        @endif
        @if(request()->end_date)
        - End Date: {{ request()->end_date }}<br>
        @endif
        @if(request()->customer_id)
        - Customer: {{ \App\Models\Customer::find(request()->customer_id)->name ?? 'N/A' }}<br>
        @endif
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Date</th>
                <th>Customer</th>
                <th>Items</th>
                <th>Subtotal</th>
                <th>Tax</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sales as $sale)
            <tr>
                <td>{{ $sale->invoice_no }}</td>
                <td>{{ $sale->sale_date->format('M d, Y') }}</td>
                <td>{{ $sale->customer->name ?? 'Walk-in Customer' }}</td>
                <td>{{ $sale->items->count() }}</td>
                <td>{{ number_format($sale->subtotal, 2) }}</td>
                <td>{{ number_format($sale->tax_amount, 2) }}</td>
                <td>{{ number_format($sale->total_amount, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <strong>Summary:</strong><br>
        Total Sales: {{ $sales->count() }}<br>
        Total Amount: ${{ number_format($sales->sum('total_amount'), 2) }}<br>
        Average Sale: ${{ number_format($sales->avg('total_amount'), 2) }}
    </div>

    <div class="footer">
        Generated by {{ config('app.name') }}
    </div>
</body>
</html>
